### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by siiiik** [OlympicCode/vHackOSBot-Java#2]
Hey thanks for the bot. I was wondering if it would be possible to auto upgrade everything except Spam, how can I do that? Thanks

**Comment by itsfolf** [comment]
There's currently no way to do that, but don't worry, I'll add it asap :D 
If you want you can join our dicord [here](https://discord.gg/52MtBDp), and I can notify and help you when its done 👍

**Comment by itsfolf** [comment]
Nevermind, I'm dumb, I actually added it a while ago and forgot :D 
You need to open your config file, set `update.listmode` to `blacklist` (as you want to blacklist spam) and then set `update.list` to `["Spam"]`.
Please tell me if it works as intended or if any error occurs 👍

**Comment by siiiik** [comment]
I did exactly that but Spam still got upgraded...

Edit: It looks like its working now but when I put it to finish everything with netcoins it still upgrades spam

**Comment by itsfolf** [comment]
If you could create a new issue for that problem it would be great!
