### ISSUE TITLE
Possible bot detection - sleep time

### ISSUE THREAD

**Issue by raspher** [OlympicCode/vHackOSBot-Java#20]
In my opinion bot is doing things too fast (who can hack into, withdraw, clear/paste in log in 4-5sec? | the same with scanning and bruteforcing).

It should be changed to a little random (or fake random) from existing 4-6 sec. to 5-10sec, even 10-15sec/target

**Comment by itsfolf** [comment]
I'll look forward into adding some feature around this

**Comment by itsfolf** [comment]
Fixed on next update!
