### ISSUE TITLE
(missing) Full Bank Detection

### ISSUE THREAD

**Issue by raspher** [OlympicCode/vHackOSBot-Java#21]
bot is trying to withdraw even when there is no space in our bank (limited to 999.999.999 in account)

**Comment by itsfolf** [comment]
Thank you for reporting this, I'll look forward into implementing it.

**Comment by ovj777** [comment]
my bot is like that too, but i think that is not problem

**Comment by itsfolf** [comment]
The only problem it can cause is that it can be detectable, other than that there's nothing

**Comment by itsfolf** [comment]
Fixed on next update
