### ISSUE TITLE
Startup - Error

### ISSUE THREAD

**Issue by yannik-dittmar** [OlympicCode/vHackOSBot-Java#26]
Sometimes the bot failes to get the response from the server.
This only occures when its services are started up.
You try to start it again until the error dosent appear anymore.
The effected services are random. Could be a threading problem.

![screenshot](https://user-images.githubusercontent.com/25822520/38500665-5f317d5c-3c0b-11e8-9c84-ae184f39dcf7.PNG)

**Comment by itsfolf** [comment]
That's due to the request speed on server upgrading, try making it higher on advanced.json

**Comment by yannik-dittmar** [comment]
ok try that out thx
