### ISSUE TITLE
smart use of boosters

### ISSUE THREAD

**Issue by AndreyBobrov** [OlympicCode/vHackOSBot-Java#27]
That is not issue, but feature request.

At this moment bot using boosters if they are available and just at regular intervals.
But, based on game mechanics, each subsequent booster gives an ever less time bonus. For example, the first used booster boosts update by 20 minutes, but last used booster gives less than minute.

Thus, the idea is to limit the waste of boosters by limiting the maximum number that can be used to speed up current list of the updates. This can be implemented by additional configuration variable, something like "update.maxBoostersPerUpdate".

Alternatively, if the bot cannot "remember" current sequence of updates, it can be implemented by limiting task's minimal remaining time, for example use boosters only if 20 or more (configurable) minutes left. So. bot will be using boosters only if it provides significal bonuses.

**Comment by itsfolf** [comment]
Done, will be released in next update.

**Comment by Ashton-Pi** [comment]
you could also divide total boosters with total netcoins, to get a price/nc, and only use a booster, if it will save at least that price
