### ISSUE TITLE
update list

### ISSUE THREAD

**Issue by ghost** [OlympicCode/vHackOSBot-Java#29]
Is there a way to config the update list and if so how do I do that, I only got Firewall auto-updating but I would also like to put Banking Protection and BruteForce in there.

**Comment by itsfolf** [comment]
Unless you changed something in your config, it upgrades the lowest app on your system, so if the firewall level is behind all the others, it will keep upgrading it until they match.

**Comment by ghost** [comment]
Yes I understand that but can I make it so it ONLY upgrades those I want ?

**Comment by itsfolf** [comment]
Yes, you can, in the config set `update.list` to the list of apps you want to be upgraded for example `["Firewall", "IP-Spoofing"]`, you can see the full list of updates by using the `apps` command.

Edit: also be sure to set `update.listmode` to `whitelist`

**Comment by ghost** [comment]
Alright thanks bro, love your bot btw! Keep up the great work and I'd love to see some updates coming soon 👍 :)

**Comment by itsfolf** [comment]
Thank you! You can check what's in the works [here](https://github.com/OlympicCode/vHackOSBot-Java/projects/1) in case you are interested ;) Have a great day!
