### ISSUE TITLE
Advanced file. 

### ISSUE THREAD

**Issue by Pajterwe** [OlympicCode/vHackOSBot-Java#30]
Hey, its my advanced config file.    "login.accesstoken": "---",
  "loglevel": "info",
  "login.uid": "---"
}

Its cant login to game. (i Have added id and Password to second config file). CMD still says me to set login data... Whats goin on?

**Comment by itsfolf** [comment]
Please provide screenshots or copies of the bot log and config files (replacing out passwords and other info)

**Comment by Pajterwe** [comment]
https://ibb.co/kKNT97

**Comment by Pajterwe** [comment]
https://ibb.co/dy70NS
https://ibb.co/ePmuhS  configs

**Comment by itsfolf** [comment]
try deleting the config files and regenerating them

**Comment by Pajterwe** [comment]
Didnt help. Its worked for me before ( and App has generated for me accesstoken in advanced file), but now it wont. Is there any Universal Accesstoken or every Player have own?

**Comment by Pajterwe** [comment]
Nevermind, problem is solved. But i have another problem. update.listmode and useboosters doesnt work for me. Its still upgrading random upgrade and not using time boosters. Can u send me preparat file with set lines? Just for example. With set options to upgrade BankingProtection, SDK, Bruteforce and use boosters.

**Comment by Pajterwe** [comment]
prepared* not preparat :D

**Comment by itsfolf** [comment]
Unless update.listmode is set to random it will never do random updates, that issue is not possible due to how the bot works. For not using boosters more information is required, be aware that the bot only uses boosters if the minimum amount of minutes configured is passed

**Comment by itsfolf** [comment]
Closed since its a different issue now, please open a new issue regarding to your problem
