### ISSUE TITLE
Bot via phone

### ISSUE THREAD

**Issue by Pajterwe** [OlympicCode/vHackOSBot-Java#31]
Is there any Way to run your bot on smartphone?

**Comment by AtjonTV** [comment]
No, you can't run the Java bot on phone, but a project called "WhiteIron" is already in development, it's a vHackOS Bot for Android.

**Comment by jawiegehts** [comment]
But I think the developer is not working on it anymore (2017 was the last activity of him)

**Comment by AtjonTV** [comment]
What are you talking about @jawiegehts ?

**Comment by jawiegehts** [comment]
The only Whiteiron bot I found was from vHackor and the last time he posted was 6 months ago

**Comment by AtjonTV** [comment]
That is not the WhiteIron I ment xD

I am developing a bot for android based on this Java bot, and i called it WhiteIron.

It's in active development and in closed beta right now.

Links:
[Website](http://projects.osmium.software/whiteiron/)
[Git Repository](https://gitlab.atvg-studios.at/atvg-studios/WhiteIron)

**Comment by jawiegehts** [comment]
Oh 
Nice!

**Comment by Pajterwe** [comment]
Ok thanks guys. Can be closed :)
