### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by KevinJordil** [OlympicCode/vHackOSBot-Java#8]
Hello,

Thx for your job !
How can I upgrade only some programs and not all (no need for antivirus and mail)?
How not to remove the bruteforce?

Thx

**Comment by itsfolf** [comment]
On the config set `update.list` to all the apps you **don't** want to be updated, for example, `["Antivirus", "Spam"]`
For the brute force removal, it uses an expression on `networking.bruteforceremove` if you want to completely disable it set it to `false`

**Comment by MuhFadjrin** [comment]
what is the code for ip spoofing, i try IPSP and IP-Spoofing but it's doesn't work

**Comment by itsfolf** [comment]
It should work, it's actually `IP-Spoofing`

**Comment by Chillandsm0ke** [comment]
Hey, thanks for your great job! 
Is it possible to configure in the config that the bot automatically deletes all system logs? Without any message? 

Thanks for your help

**Comment by itsfolf** [comment]
@Chillandsm0ke Just set `networking.logMessage` to nothing (`""`).

**Comment by Chillandsm0ke** [comment]
Thanks for your fast answer!

**Comment by itsfolf** [comment]
Closed due to inactivity, please reopen as necessary.
